name: part_time_model
description: Financial modeling software.
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  meta: any

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
